version: "3.7"

services:
  web:
    build:
      context: .
      dockerfile: .docker/ruby/Dockerfile
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 3000 -b 0.0.0.0"
    depends_on:
      - postgres
      - redis
      - sidekiq
    environment:
      - DATABASE_URL=postgres://postgres:1234@postgres:5432/justask_development
      - REDIS_URL=redis://redis:6379/1
      - RAILS_ENV=production
      - RAILS_SERVE_STATIC_FILES=true
      - HOSTNAME=nightspring.net
    volumes:
      - .:/app
      - cache:/cache
    ports:
      - "3000:3000"
    restart: unless-stopped

  sidekiq:
    build:
      context: .
      dockerfile: .docker/ruby/Dockerfile
    command: bundle exec sidekiq
    depends_on:
      - redis
      - postgres
    environment:
      - DATABASE_URL=postgres://postgres:1234@postgres:5432/justask_development
      - REDIS_URL=redis://redis:6379/1
      - RAILS_ENV=production
    volumes:
      - .:/app
    restart: unless-stopped

  redis:
    image: redis:6.2.10-alpine
    ports:
      - "6379:6379"
    restart: unless-stopped

  postgres:
    image: postgres:10.12
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1234
      POSTGRES_DB: justask_development
    ports:
      - "5432:5432"
    volumes:
      - db:/var/lib/postgresql/data
    restart: unless-stopped

volumes:
  db:
  cache:
