version: "3.7"

services:
  web:
    build:
      context: .
      dockerfile: .docker/ruby/Dockerfile
    command: bash -c "rm -f tmp/pids/server.pid && rdebug-ide --skip_wait_for_start --host 0.0.0.0 --port 1234 --dispatcher-port 26162 -- bin/rails s -p 3012 -b '0.0.0.0'"
    depends_on:
      - postgres
      - redis
      - sidekiq
    env_file:
      - .env
    environment:
      - SPROCKETS_CACHE=/cache
      - DATABASE_URL=postgres://postgres:justask@postgres/justask_development?pool=25
      - REDIS_URL=redis://redis:6379
      - RAILS_ENV=production
      - RAILS_SERVE_STATIC_FILES=true
      - HOSTNAME=spring.love4eva.net
    volumes:
      - ./:/app
      - cache:/cache
    ports:
      - 192.168.1.219:3012:3012
      - 1234:1234
    restart: unless-stopped

  sidekiq:
    build:
      context: .
      dockerfile: .docker/ruby/Dockerfile
    command: bundle exec sidekiq
    depends_on:
      - redis
    volumes:
      - ./:/app
    env_file:
      - .env
    environment:
      - DATABASE_URL=postgres://postgres:justask@postgres/justask_development?pool=25
      - REDIS_URL=redis://redis:6379
      - RAILS_ENV=production
    restart: unless-stopped

  redis:
    image: redis:6.2.10-alpine
    ports:
       - 6381:6381
    restart: unless-stopped

  postgres:
    image: postgres:10.12
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1234
      POSTGRES_PORT: 5432
      POSTGRES_DB: justask_development
    volumes:
      - ./dbb:/var/lib/postgresql/data
    restart: unless-stopped

volumes:
  db:
  cache:
