name: Bug Report
description: If something isn't working as expected
labels: [bug]
body:
  - type: markdown
    attributes:
      value: |
        Before opening an issue, please make sure to check if the [issue tracker](https://github.com/Retrospring/retrospring/issues?q=is%3Aissue+label%3Abug) in case it has been previously reported or fixed.
  - type: textarea
    attributes:
      label: Steps to reproduce the problem
      description: What were you trying to do?
      value: |
        1.
        2.
        3.
        ...
    validations:
      required: true
  - type: textarea
    attributes:
      label: Expected behaviour
      description: What should have happened?
    validations:
      required: true
  - type: textarea
    attributes:
      label: Actual behaviour
      description: What happened?
    validations:
      required: true
  - type: textarea
    attributes:
      label: Detailed description
    validations:
      required: false
  - type: textarea
    attributes:
      label: Specifications
      description: |
        If you host Retrospring, what version/commit hash of Retrospring did this issue occur in?

        If a front-end issue, what browser and operating systems were you using?
      placeholder: |
        Retrospring 1970.0101.0
        Ruby 3.1.3
        Node.js 18.13.0

        Google Chrome 112
        Firefox 109.0

        etc...
    validations:
      required: true
