name: Feature Request
description: If you have a suggestion
labels: [suggestion]
body:
  - type: markdown
    attributes:
      value: |
        Please use a concise and distinct title for the issue.
  - type: textarea
    attributes:
      label: Pitch
      description: Describe your idea for a feature. Please check our [issue tracker](https://github.com/Retrospring/retrospring/issues?q=is%3Aissue+label%3Asuggestion) to make sure it has not already been suggested/implemented/turned down before.
    validations:
      required: true
  - type: textarea
    attributes:
      label: Motivation
      description: Why do you think this feature is needed? Who would benefit from it?
    validations:
      required: true
